SELECT * FROM INE_ENTIDAD_2020;
/*Rectify the accent mistakes in the 'NOM_ENT' column*/
UPDATE INE_DISTRITO_2020
SET NOM_ENT = 'Ciudad de México'
WHERE NOM_ENT LIKE 'Ciudad de M%';

UPDATE INE_DISTRITO_2020
SET NOM_ENT = 'Michoacán de Ocampo'
WHERE NOM_ENT LIKE 'Michoac%';

UPDATE INE_DISTRITO_2020
SET NOM_ENT = 'México'
WHERE NOM_ENT LIKE 'M%xico';

UPDATE INE_DISTRITO_2020
SET NOM_ENT = 'Nuevo León'
WHERE NOM_ENT LIKE 'Nuevo Le%n';

UPDATE INE_DISTRITO_2020
SET NOM_ENT = 'Yucatán'
WHERE NOM_ENT LIKE 'Yuca%';

UPDATE INE_DISTRITO_2020
SET NOM_ENT = 'Querétaro'
WHERE NOM_ENT LIKE 'Quer%';

UPDATE INE_DISTRITO_2020
SET NOM_ENT = 'San Luis Potosí'
WHERE NOM_ENT LIKE 'San Luis%';

/*The updated INE_DISTRITO_2020*/
SELECT * FROM INE_DISTRITO_2020;

/*Address accent mistakes in the 'COMPLEJIDA' column*/
UPDATE INE_DISTRITO_2020
SET COMPLEJIDA = 'Concentración Media'
WHERE COMPLEJIDA LIKE 'Concentraci%n Media';

SELECT * FROM INE_DISTRITO_2020;

/*Selecting unique values from the 'NOM_ENT' column to eliminate duplicates*/
SELECT DISTINCT NOM_ENT FROM INE_DISTRITO_2020;

/*Adding new columns based on the 'COMPLEJIDA' values*/
ALTER TABLE INE_DISTRITO_2020
ADD ALT_CON_1 INT, ALT_CON_2 INT, CON_MED INT, CONC1 INT, CONC2 INT, DIS1 INT, DISP2 INT, MUY_DIS1 INT, MUY_DISP2 INT;

/*Setting dummy variables for 'COMPLEJIDA' values*/
UPDATE INE_DISTRITO_2020
SET ALT_CON_1 = 0, ALT_CON_2 = 0, CON_MED = 0, CONC1 = 0, CONC2 = 0, DIS1 = 0, DISP2 = 0, MUY_DIS1 = 0, MUY_DISP2 = 0;

UPDATE INE_DISTRITO_2020
SET ALT_CON_1 = 1
WHERE COMPLEJIDA = 'Altamente Concentrado 1';

UPDATE INE_DISTRITO_2020
SET ALT_CON_2 = 1
WHERE COMPLEJIDA = 'Altamente Concentrado 2';

UPDATE INE_DISTRITO_2020
SET CON_MED = 1
WHERE COMPLEJIDA = 'Concentración Media';

UPDATE INE_DISTRITO_2020
SET CONC1 = 1
WHERE COMPLEJIDA = 'Concentrado 1';

UPDATE INE_DISTRITO_2020
SET CONC2 = 1
WHERE COMPLEJIDA = 'Concentrado 2';

UPDATE INE_DISTRITO_2020
SET DIS1 = 1
WHERE COMPLEJIDA = 'Disperso 1';

UPDATE INE_DISTRITO_2020
SET DISP2 = 1
WHERE COMPLEJIDA = 'Disperso 2';

UPDATE INE_DISTRITO_2020
SET MUY_DIS1 = 1
WHERE COMPLEJIDA = 'Muy Disperso 1';

UPDATE INE_DISTRITO_2020
SET MUY_DISP2 = 1
WHERE COMPLEJIDA = 'Muy Disperso 2';

/*The final updated INE_DISTRITO_2020*/
SELECT * FROM INE_DISTRITO_2020;









